WebElReyCan/Models/Mascota.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace WebElReyCan.Models
{
    [Table("Turno")]
    public class Mascota
    {
        
        
        [Key]
        public int Id { get; set; }
        [Column(TypeName = "date")]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}")]
        public DateTime Fecha { get; set; }

        

        [DisplayFormat(DataFormatString = "{0:HH:mm}")]
        [Column(TypeName = "varchar")]
        public string Hora { get; set; }
        [Required(ErrorMessage = "Campo Requerido.")]
        [StringLength(50)]
        public string NombreMascota { get; set; }
        [StringLength(50)]
        public string Raza { get; set; }
        public int Edad { get; set; }
        [Required(ErrorMessage = "Campo Requerido.")]
        [StringLength(50)]
        public string NombreDueño { get; set; }
        [Required(ErrorMessage = "Campo Requerido.")]
        [StringLength(50)]
        public string Celular { get; set; }
    }
}

WebElReyCan/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebElReyCan.Controllers
{
    public class HomeController : Controller
    {
        // GET: Home
        public ActionResult Index()
        {
            ViewBag.Fecha = DateTime.Now.ToShortDateString();
            return View();
        }
    }
}

WebElReyCan/Controllers/MascotaController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebElReyCan.Data;
using WebElReyCan.Models;

namespace WebElReyCan.Controllers
{
    public class MascotaController : Controller
    {
        private MascotaDbContext context = new MascotaDbContext();
        public ActionResult Index()
        {
            var mascotas = context.Mascotas.ToList();
            return View("Index", mascotas);
        }
        public ActionResult Turnos()
        {
            DateTime fechaHoy = DateTime.Today;

            List<Mascota> mascotasHoy = (from t in context.Mascotas
                                     where t.Fecha == fechaHoy
                                     select t).ToList();

            return View("Index", mascotasHoy);
        }
        public ActionResult Create()
        {
            Mascota mascota = new Mascota();
            return View("Create", mascota);
        }
        [HttpPost]
        public ActionResult Create(Mascota mascota)
        {
            if (ModelState.IsValid)
            {
                context.Mascotas.Add(mascota);
                context.SaveChanges();
                return RedirectToAction("Index");
            }
            return View("create", mascota);
        }
        public ActionResult Delete(int id)
        {
            Mascota mascota = context.Mascotas.Find(id);
            if (mascota != null)
            {
                return View("Delete", mascota);
            }
            else
            {
                return HttpNotFound();
            }
        }
        [HttpPost]
        [ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            Mascota mascota = context.Mascotas.Find(id);

            context.Mascotas.Remove(mascota);
            context.SaveChanges();

            return RedirectToAction("Index");
        }
        public ActionResult Edit(int id)
        {
            Mascota mascota = context.Mascotas.Find(id);

            if (mascota != null)
            {
                return View("Edit", mascota);
            }
            else
            {
                return HttpNotFound();
            }
        }
        [HttpPost]
        [ActionName("Edit")]
        public ActionResult EditConfirmed(Mascota mascota)
        {
            if (ModelState.IsValid)
            {
                context.Entry(mascota).State = EntityState.Modified;
                context.SaveChanges();
                return RedirectToAction("Index");
            }
            return View("Edit", mascota);
        }
        
        public ActionResult SearchByName(string nombreMascota)
        {
            if (nombreMascota == null)
            {
                return RedirectToAction("Index");
            }
            List<Mascota> mascotas = (
                from o in context.Mascotas
                where o.NombreMascota == nombreMascota
                select o).ToList();
            return View("Index", mascotas);
        }
        public ActionResult TraerPorCelular(string celular)
        {
            if (celular == null)
            {
                return RedirectToAction("Index");
            }
            List<Mascota> mascotas = (
                from o in context.Mascotas
                where o.Celular == celular
                select o).ToList();
            return View("Index", mascotas);
        }





    }
}

WebElReyCan/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Index";
}
<h1>Fecha: @ViewBag.Fecha</h1>
<h1>Bienvenidos al Sitio Web</h1>

<div>

</div>

WebElReyCan/Views/Mascota/Create.cshtml
@model WebElReyCan.Models.Mascota

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Create</title>
</head>
<body>
    @using (Html.BeginForm("Create", "Mascota", FormMethod.Post))
    {
        <table>
            <tr>
                <td>@Html.LabelFor(model => model.Fecha)</td>
                <td>
                    @Html.EditorFor(model => model.Fecha)
                    @Html.ValidationMessageFor(model => model.Fecha)
                </td>
            </tr>
            <tr>
                <td>@Html.LabelFor(model => model.Hora)</td>
                <td>
                    @Html.EditorFor(model => model.Hora)
                    @Html.ValidationMessageFor(model => model.Hora)
                </td>
            </tr>
            <tr>
                <td>@Html.LabelFor(model => model.NombreMascota)</td>
                <td>
                    @Html.EditorFor(model => model.NombreMascota)
                    @Html.ValidationMessageFor(model => model.NombreMascota)
                </td>
            </tr>
            <tr>
                <td>@Html.LabelFor(model => model.Raza)</td>
                <td>
                    @Html.EditorFor(model => model.Raza)
                    @Html.ValidationMessageFor(model => model.Raza)
                </td>
            </tr>
            <tr>
                <td>@Html.LabelFor(model => model.Edad)</td>
                <td>
                    @Html.EditorFor(model => model.Edad)
                    @Html.ValidationMessageFor(model => model.Edad)
                </td>
            </tr>
            <tr>
                <td>@Html.LabelFor(model => model.NombreDueño)</td>
                <td>
                    @Html.EditorFor(model => model.NombreDueño)
                    @Html.ValidationMessageFor(model => model.NombreDueño)
                </td>
            </tr>
            <tr>
                <td>@Html.LabelFor(model => model.Celular)</td>
                <td>
                    @Html.EditorFor(model => model.Celular)
                    @Html.ValidationMessageFor(model => model.Celular)
                </td>
            </tr>


        </table>
        <p>
            <input type="submit" value=" Create" />
        </p>
        <p>
            @Html.ActionLink("Back to List", "Index", "Mascota")
        </p>


    }
</body>
</html>

WebElReyCan/Views/Mascota/Delete.cshtml
@model WebElReyCan.Models.Mascota

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Delete</title>
</head>
<body>
    <h2> Eliminar Mascota</h2>
    @using (Html.BeginForm("Delete", "Mascota", FormMethod.Post))
    {
        <fieldset>
            <legend>Detalle</legend>
            <div class="display-label">
                @Html.DisplayNameFor(model => model.Fecha)
            </div>
            <div class=" display-text">
                @Html.DisplayFor(model => model.Fecha)
            </div>
            <div class="display-label">
                @Html.DisplayNameFor(model => model.Hora)
            </div>
            <div class=" display-text">
                @Html.DisplayFor(model => model.Hora)
            </div>
            <div class="display-label">
                @Html.DisplayNameFor(model => model.NombreMascota)
            </div>
            <div class=" display-text">
                @Html.DisplayFor(model => model.NombreMascota)
            </div>
            <div class="display-label">
                @Html.DisplayNameFor(model => model.Raza)
            </div>
            <div class=" display-text">
                @Html.DisplayFor(model => model.Raza)
            </div>
            <div class="display-label">
                @Html.DisplayNameFor(model => model.Edad)
            </div>
            <div class=" display-text">
                @Html.DisplayFor(model => model.Edad)
            </div>
            <div class="display-label">
                @Html.DisplayNameFor(model => model.NombreDueño)
            </div>
            <div class=" display-text">
                @Html.DisplayFor(model => model.NombreDueño)
            </div>
            <div class="display-label">
                @Html.DisplayNameFor(model => model.Celular)
            </div>
            <div class=" display-text">
                @Html.DisplayFor(model => model.Celular)
            </div>
        </fieldset>

        <p>
            <input type="submit" value="Delete" />
        </p>
    }
    <p>
        @Html.ActionLink("Back to List", "Index", "Mascota")
    </p>
</body>
</html>

WebElReyCan/Views/Mascota/Edit.cshtml
@model WebElReyCan.Models.Mascota

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Edit</title>
</head>
<body>
    @using (Html.BeginForm("Edit", "Mascota", FormMethod.Post))
    {
        @Html.HiddenFor(model => model.Id)
        <table>
            <tr>
                <td>@Html.LabelFor(model => model.Fecha)</td>
                <td>
                    @Html.EditorFor(model => model.Fecha)
                    @Html.ValidationMessageFor(model => model.Fecha)
                </td>
            </tr>
            <tr>
                <td>@Html.LabelFor(model => model.Hora)</td>
                <td>
                    @Html.EditorFor(model => model.Hora)
                    @Html.ValidationMessageFor(model => model.Hora)
                </td>
            </tr>
            <tr>
                <td>@Html.LabelFor(model => model.NombreMascota)</td>
                <td>
                    @Html.EditorFor(model => model.NombreMascota)
                    @Html.ValidationMessageFor(model => model.NombreMascota)
                </td>
            </tr>
            <tr>
                <td>@Html.LabelFor(model => model.Raza)</td>
                <td>
                    @Html.EditorFor(model => model.Raza)
                    @Html.ValidationMessageFor(model => model.Raza)
                </td>
            </tr>
            <tr>
                <td>@Html.LabelFor(model => model.Edad)</td>
                <td>
                    @Html.EditorFor(model => model.Edad)
                    @Html.ValidationMessageFor(model => model.Edad)
                </td>
            </tr>
            <tr>
                <td>@Html.LabelFor(model => model.NombreDueño)</td>
                <td>
                    @Html.EditorFor(model => model.NombreDueño)
                    @Html.ValidationMessageFor(model => model.NombreDueño)
                </td>
            </tr>
            <tr>
                <td>@Html.LabelFor(model => model.Celular)</td>
                <td>
                    @Html.EditorFor(model => model.Celular)
                    @Html.ValidationMessageFor(model => model.Celular)
                </td>
            </tr>
        </table>
        <p>
            <input type="submit" value="Save" />
        </p>
    

    }
    @Html.ActionLink("Back to List", "Index", "Mascota")
</body>
</html>

WebElReyCan/Views/Mascota/Index.cshtml
@model IEnumerable<WebElReyCan.Models.Mascota>

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
</head>
<body>
    <table>
        <tr>
            <td></td>
            <td>
                @using (Html.BeginForm("Create", "Mascota", FormMethod.Get))
                {
                    <input type="submit" value="Crear Nuevo Turno" />
                }
            </td>
        </tr>
        <tr>

            <td>
                @using (Html.BeginForm("SearchByName", "Mascota", FormMethod.Get))
                {
                    @Html.Label("Nombre Mascota:")
                    @Html.TextBox("nombreMascota", null)

                    <input type="submit" value="Get" />
                }
            </td>
        </tr>
        <tr>

            <td>
                @using (Html.BeginForm("TraerPorCelular", "Mascota", FormMethod.Get))
                {
                    @Html.Label("Numero Celular:")
                    @Html.TextBox("celular", null)

                    <input type="submit" value="Get" />
                }
            </td>
        </tr>
        <tr>

            <td>
                @using (Html.BeginForm("Index", "Mascota", FormMethod.Get))
                {
                    <input type="submit" value="Traer Todas" />
                }
            </td>
        </tr>
        <tr>

            <td>
                @using (Html.BeginForm("Turnos", "Mascota", FormMethod.Get))
                {
                    <input type="submit" value="Ver turnos de hoy" />
                }
            </td>
        </tr>

    </table>
    <table>
        <tr>
            <th>@Html.DisplayNameFor(model => model.Fecha)</th>
            <th>@Html.DisplayNameFor(model => model.Hora)</th>
            <th>@Html.DisplayNameFor(model => model.NombreMascota)</th>
            <th>@Html.DisplayNameFor(model => model.Raza)</th>
            <th>@Html.DisplayNameFor(model => model.Edad)</th>
            <th>@Html.DisplayNameFor(model => model.NombreDueño)</th>
            <th>@Html.DisplayNameFor(model => model.Celular)</th>
            <th>Delete</th>
            <th>Edit</th>
        </tr>
        @foreach (var item in Model)
        {
    <tr>
        <td>@Html.DisplayFor(modelItem => item.Fecha)</td>
        <td>@Html.DisplayFor(modelItem => item.Hora)</td>
        <td>@Html.DisplayFor(modelItem => item.NombreMascota)</td>
        <td>@Html.DisplayFor(modelItem => item.Raza)</td>
        <td>@Html.DisplayFor(modelItem => item.Edad)</td>
        <td>@Html.DisplayFor(modelItem => item.NombreDueño)</td>
        <td>@Html.DisplayFor(modelItem => item.Celular)</td>
        <td>
            @Html.ActionLink("Delete", "Delete", new { id = item.Id })
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id = item.Id })
        </td>

    </tr>


        }
    </table>
    @section sidebar {
        <h2>Como cuidar el pelo de tu mascota</h2>
        <p>Cepillar de manera regular, con el cepillo idóneo y en el momento adecuado </p>
        <p>Bañar acorde al pelo de cada perro </p>

    }

</body>
</html>

WebElReyCan/Views/Shared/_LayoutPage1.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="~/Content/main.css" rel="stylesheet" />
</head>
<body>
    <header>
        <section class="banner"></section>
        <section class="logo"></section>
        <section class="login">
            <h3>Login</h3>
            <div>
                <label>Nombre</label>
                <input type="text">
            </div>
            <div>
                <label>Email</label> <input type="email">
            </div>
            <br>
            <button class="btn">
                Enviar
            </button>

        </section>
    </header>
    <nav>
        <div>
            @Html.ActionLink("Inicio", "Index", "Home") | 
        </div>

        <div>
            @Html.ActionLink("Turnos", "Index", "Mascota")
        </div>
    </nav>
    <main>
        <aside class="left">
            @if (IsSectionDefined("sidebar"))
            {
                @RenderSection("sideBar")
            }
            else
            {               
                    <h2>Peluqueros recomendados:</h2>
                <ul>
                    <li><a href="https://es.wikipedia.org/wiki/Peluquero_canino">El arte de la peluquería</a></li>
                </ul>
            }
        </aside>
        <article class="article">
            @RenderBody()
        </article>

    </main>
    <footer>
        elreycan@email.com
    </footer>


</body>
</html>